### ISSUE TITLE
Feature - Hide if time tracking module is not enabled

### ISSUE THREAD

**Issue by Winslow-AT** [LeviticusMB/bestest_timer#8]
Hello,

we work with mulitple projects and some of them have the time tracking module not enabled, but Punch Clock is still showing up and returning the no_permission error if someone tries to commit their time.

If possible please either hide the button completely in the view or change the error message accordingly if this is the case.

Thanks

**Comment by LeviticusMB** [comment]
I prefer not to hide it since then the rest of the UI will move around when you switch projects. But I've disabled the button and provided a proper message for this case.

Please have a look in the `v1.2` branch (unreleased) and see if you think it's acceptable.

Oh and if you could provide a translation for the key below, that would be great too:

```
    not_enabled: "Time tracking not enabled for %{project}."
```
